### ISSUE TITLE
./yolov9-tensorrt.exe    ./model.engine  ./1096.jpg    Error Code 1: Cuda Runtime (an illegal memory access was encountered)

### ISSUE THREAD

**Issue by molyswu** [spacewalk01/tensorrt-yolov9#13]
Hi, 
  ./yolov9-tensorrt.exe    ./model.engine  ./1096.jpg     error as follower:
   [04/30/2024-10:14:29] [E] [TRT] 1: [weightConverters.cu::nvinfer1::rt::cuda::padCaskConvWeight::166] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
CUDA error 700 at F:\TensorRT-YOLOv9\src\yolov9.cpp:97Assertion failed: 0, file F:\TensorRT-YOLOv9\src\yolov9.cpp, line 97

1096.jpg   :409*962

**Comment by spacewalk01** [comment]
Hi, width=409 and height=962 image right? I will test it. Thank you for informing

**Comment by spacewalk01** [comment]
I have tested it with 427x640 image and it worked:
![image](https://github.com/spacewalk01/TensorRT-YOLOv9/assets/6389915/624f07a6-2d71-43c8-b0b9-0e939b520fc3)

**Comment by spacewalk01** [comment]
Will you send me  your onnx model?

**Comment by molyswu** [comment]
The weights. zip file contains onnx and jpg images of the target copper surface

**Comment by molyswu** [comment]
onnx

**Comment by molyswu** [comment]
156M File size too big: 25 MB

**Comment by molyswu** [comment]
![1022](https://github.com/spacewalk01/TensorRT-YOLOv9/assets/11438784/fd668bf6-f64b-49c2-9a30-7803585a9b9e)

**Comment by molyswu** [comment]
Do you have a cloud drive that allows you to upload ONNX files？

**Comment by spacewalk01** [comment]
Is it a costumized model? what is the number of classes of your model?

**Comment by molyswu** [comment]
Locate the incorrect statement：
CUDA_CHECK(cudaMemcpyAsync(cpu_output_buffer, gpu_buffers[1], num_detections * detection_attribute_size * sizeof(float), cudaMemcpyDeviceToHost, cuda_stream));
CUDA_CHECK(cudaStreamSynchronize(cuda_stream));

**Comment by molyswu** [comment]
It is costumized mode

**Comment by molyswu** [comment]
2 classes

**Comment by molyswu** [comment]
![3F2C1C636248](https://github.com/spacewalk01/TensorRT-YOLOv9/assets/11438784/2c3284e3-e730-42cd-a509-47b9793fe71b)

**Comment by spacewalk01** [comment]
`detection_attribute_size * num_detections == 84 x 8400` for default 80 classes. So in your case, when the number of classes is 2, it should be `6 x 8400`. Will you print out result? You can also analyze onnx file using https://netron.app application. It shows something like this:
 
![image](https://github.com/spacewalk01/TensorRT-YOLOv9/assets/6389915/ae97d998-5c0a-4660-a34b-0b45be41befd)

**Comment by molyswu** [comment]
I can't find this line in your code：“detection_attribute_size * num_detections == 84 x 8400”，I don't know where to modify it

**Comment by molyswu** [comment]
CONF_THRESH = 0.3
IOU_THRESHOLD = 0.2
NUM_DETECTIONS = 8400
LEN_ONE_RESULT = 84

**Comment by molyswu** [comment]
python

**Comment by spacewalk01** [comment]
You trained your model with 2 classes but your onnx file has 80 classes. I think that is the problem. You need to set the number of classes of your model into 2 in reparameterize.py.

**Comment by spacewalk01** [comment]
https://github.com/spacewalk01/TensorRT-YOLOv9/blob/main/reparameterize.py

**Comment by spacewalk01** [comment]
In line 8, fix it as follows: model = Model(cfg, ch=3, nc=2, anchors=3)

**Comment by molyswu** [comment]
python yolov9_trt.py --engine yolov9-c.engine --data images --outdir output     error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\yolov9\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "F:\TensorRT-YOLOv9\python\yolov9_trt.py", line 394, in run
    batch_image_raw, use_time = self.yolov9_wrapper.infer(self.yolov9_wrapper.get_raw_image(self.image_path_batch))
  File "\TensorRT-YOLOv9\python\yolov9_trt.py", line 170, in infer
    result_boxes, result_scores, result_classid = self.post_process(
  File "F:\TensorRT-YOLOv9\python\yolov9_trt.py", line 293, in post_process
    pred = np.reshape(output, (-1, NUM_DETECTIONS)).T
  File "C:\ProgramData\anaconda3\envs\yolov9\lib\site-packages\numpy\core\fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\ProgramData\anaconda3\envs\yolov9\lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 105966 into shape (8400)

**Comment by molyswu** [comment]
I modified the program and there is the same issue：In line 8, fix it as follows: model = Model(cfg, ch=3, nc=2, anchors=3)

**Comment by molyswu** [comment]
File "C:\ProgramData\anaconda3\envs\yolov9\lib\site-packages\numpy\core\fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\ProgramData\anaconda3\envs\yolov9\lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 141288 into shape (8400)
